spring.application.name=demo

# Настройки подключения к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/main
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false